### ISSUE TITLE
CHD: fix block address calculations

### ISSUE THREAD

**Issue by Mr-Jake** [libretro/beetle-saturn-libretro#4]
Before the rebase there were issues reported regarding multi-data-track CHDs, specifically the game "Last Bronx".

There was a commit merged March 19, 2022, that apparently fixed this issue.
https://github.com/libretro-mirrors/beetle-saturn-libretro/pull/215

I currently don't have the game Last Bronx to test the rebase, but looking at the rebase code it appears this commit was not included. I thought it would be helpful to point this out before Last Bronx issues are reported again.

Many thanks for the rebase. It is very much appreciated.

**Comment by LibretroAdmin** [comment]
Hi there,

this has now been backported -
https://github.com/libretro/beetle-saturn-libretro/commit/5e840af3be9b36be3473f7f0edb8bd66223f7ab2

Hopefully it all works.

**Comment by LilaQ** [comment]
Has there been a regression with this? Can't boot "Last Bronx" on latest artifact (tried multiple dumps).
