### ISSUE TITLE
Core Aspect Ratio Option

### ISSUE THREAD

**Issue by Jobima1st** [libretro/beetle-saturn-libretro#48]
Seems beetle saturn is missing Core Aspect Ratio Option that other beetle cores had

**Comment by Kelvfimer** [comment]
go to settings->video and there is a core aspect ration option

**Comment by Jobima1st** [comment]
> go to settings->video and there is a core aspect ration option

that work but still it should be there in the core options like other cores

**Comment by Jobima1st** [comment]
I note there are already open issue for this https://github.com/libretro/beetle-saturn-libretro/issues/28
so I will close this
